-- Phase 9A: BNS monthly retail coal series — NO PRICE INSERTS.
--
-- Dataset: «Розничные цены на отдельные товары и услуги в Республике Казахстан»
-- Каталог: https://stat.gov.kz/ru/industries/economy/prices/spreadsheets/?name=19087
--
-- Проверено (не вслепую):
--   август 2026 — https://stat.gov.kz/api/iblock/element/347970/file/ru/
--     дата опубликования в файле: 09.09.2026
--   август 2025 — https://stat.gov.kz/api/iblock/element/347969/file/ru/
--
-- Структура (сопоставима по смыслу, не идентична составу строк):
--   листы 1 продовольствие / 2 непродовольствие / 3 платные услуги;
--   колонки: Республика Казахстан + города (Астана, Алматы, Шымкент, областные центры);
--   единица: тенге (за кг / штуку / услугу — зависит от товара);
--   это средние розничные цены CPI-наблюдения (методика ИПЦ), не акиматские point prices.
--
-- Уголь:
--   строки «уголь каменный» НЕТ.
--   «Активированный уголь, 10 таблеток» — лекарство, не коммунально-бытовой уголь.
--   «Дрова, куб м» — не уголь.
--
-- Дополнительно проверен name=19078 (цены производителей), август 2026, iblock 347976:
--   лист «4.» — «Уголь каменный энергетический», тонна, внутренний рынок:
--   Республика Казахстан 10 528 ₸/т; Карагандинская 10 736 ₸/т (август 2026).
--   Это PRODUCER PRICE, не розница населению. Не импортировать в retail_coal_observations.
--
-- Поэтому INSERT в retail_coal_observations из BNS XLSX НЕ делается.
-- CPI +8,6% за 2024 (https://stat.gov.kz/ru/industries/economy/prices/publications/280679/)
-- не является KZT/t и не вставляется сюда.
--
-- Source bnsRetailGoodsPrices создаётся в seed_phase9_retail_coal_observations.sql.
-- Этот файл можно выполнить: он только сообщает статус.

SELECT 'phase9_bns_retail_prices: coal row not present in name=19087 XLSX; no price rows'::text AS status;
