import {
  INFRA_CLASS,
  INFRA_MEASURE,
  INFRA_NODE_TYPE,
  INFRA_RELATION,
} from './registry.js'

const SRC = Object.freeze({
  bogatyrKomir: 'bogatyrKomir',
  bogatyrCpt: 'bogatyrCpt',
  bogatyrStorage2024: 'bogatyrStorage2024',
  ktzBogatyrLoading2025: 'ktzBogatyrLoading2025',
  shubarkolErg: 'shubarkolErg',
  kaseShukAr2023: 'kaseShukAr2023',
  ktzShubarkolExport2025: 'ktzShubarkolExport2025',
  karazhyraAbout: 'karazhyraAbout',
  ktzKarazhyraDegelen2025: 'ktzKarazhyraDegelen2025',
  maikubenCompany: 'maikubenCompany',
  maikubenHistory: 'maikubenHistory',
  kaseMkbwAr: 'kaseMkbwAr',
})

function node(partial) {
  return Object.freeze({
    sourceId: null,
    limitations: null,
    notes: null,
    ...partial,
  })
}

function link(partial) {
  return Object.freeze({
    limitations: null,
    ...partial,
  })
}

function obs(partial) {
  return Object.freeze({
    linkId: null,
    qualifier: 'exact',
    ...partial,
  })
}

export const INFRASTRUCTURE_SOURCES = Object.freeze({
  [SRC.bogatyrCpt]: {
    id: SRC.bogatyrCpt,
    organization: 'ТОО «Богатырь Комир»',
    publication: 'Циклично-поточная технология (ЦПТ) и структура предприятия',
    url: 'https://www.bogatyr.kz/ru/projects/',
  },
  [SRC.bogatyrStorage2024]: {
    id: SRC.bogatyrStorage2024,
    organization: 'ТОО «Богатырь Комир»',
    publication: 'Сообщение о вводе угольных складов',
    url: 'https://www.bogatyr.kz/ru/press/news/2545',
  },
  [SRC.ktzBogatyrLoading2025]: {
    id: SRC.ktzBogatyrLoading2025,
    organization: 'АО «НК «Қазақстан темір жолы»',
    publication: 'Итоги перевозок с грузоотправителями: погрузка Богатырь Комир',
    url: 'https://railways.kz/ru/news2025/v-ktzh-obsudili-itogi-perevozok-s-gruzootpravitelyami/',
  },
  [SRC.ktzShubarkolExport2025]: {
    id: SRC.ktzShubarkolExport2025,
    organization: 'АО «НК «Қазақстан темір жолы»',
    publication: 'Экспортная погрузка угля Шубарколь комир, июнь 2025',
    url: 'https://railways.kz/kk/news2025/temirzhol-kligimen-eksportty-kmir-tieu-tarihi-rekorda-zhetti/',
  },
  [SRC.karazhyraAbout]: {
    id: SRC.karazhyraAbout,
    organization: 'АО «Каражыра»',
    publication: 'О компании',
    url: 'https://www.karazhyra.kz/about/',
  },
  [SRC.ktzKarazhyraDegelen2025]: {
    id: SRC.ktzKarazhyraDegelen2025,
    organization: 'АО «НК «Қазақстан темір жолы»',
    publication: 'Мониторинг погрузки угля: станция Дегелен / АО «Каражыра»',
    url: 'https://railways.kz/ru/news2025/zheleznodorozhniki-vostochnogo-kazahstana-proveli-monitoring-nal/',
  },
  [SRC.maikubenCompany]: {
    id: SRC.maikubenCompany,
    organization: 'АО «Майкубен-Вест»',
    publication: 'О компании',
    url: 'https://maikuben.kz/company/',
  },
  [SRC.maikubenHistory]: {
    id: SRC.maikubenHistory,
    organization: 'АО «Майкубен-Вест»',
    publication: 'История предприятия',
    url: 'https://maikuben.kz/company/history/',
  },
})

export const INFRASTRUCTURE_NODES = Object.freeze([
  node({
    id: 'bogatyr-producer',
    producerId: 'bogatyr',
    nodeType: INFRA_NODE_TYPE.PRODUCER,
    displayName: 'ТОО «Богатырь Комир»',
    categoryLabel: 'ПРОИЗВОДИТЕЛЬ',
    chainOrder: null,
    classification: INFRA_CLASS.RELATIONSHIP_VERIFIED,
    sourceId: SRC.bogatyrKomir,
  }),
  node({
    id: 'bogatyr-mine',
    producerId: 'bogatyr',
    nodeType: INFRA_NODE_TYPE.MINE,
    displayName: 'Разрез Богатырь',
    categoryLabel: 'ДОБЫЧА',
    chainOrder: 1,
    classification: INFRA_CLASS.RELATIONSHIP_VERIFIED,
    sourceId: SRC.bogatyrKomir,
    limitations: 'Производственная мощность 42 млн т/год не является инфраструктурной мощностью.',
  }),
  node({
    id: 'bogatyr-cpt',
    producerId: 'bogatyr',
    nodeType: INFRA_NODE_TYPE.PROCESSING,
    displayName: 'Циклично-поточная технология',
    categoryLabel: 'ОБРАБОТКА',
    chainOrder: 2,
    classification: INFRA_CLASS.QUANTITATIVE_VERIFIED,
    sourceId: SRC.bogatyrCpt,
    limitations: 'Протяжённость и состав оборудования не равны годовой пропускной способности.',
  }),
  node({
    id: 'bogatyr-loading',
    producerId: 'bogatyr',
    nodeType: INFRA_NODE_TYPE.LOADING,
    displayName: 'Автоматическая вагонная погрузка',
    categoryLabel: 'ПОГРУЗКА',
    chainOrder: 3,
    classification: INFRA_CLASS.RELATIONSHIP_VERIFIED,
    sourceId: SRC.bogatyrCpt,
    limitations: 'Наличие пункта не доказывает текущую годовую мощность погрузки.',
  }),
  node({
    id: 'bogatyr-collection',
    producerId: 'bogatyr',
    nodeType: INFRA_NODE_TYPE.RAIL_STATION,
    displayName: 'Сборочные станции',
    categoryLabel: 'Ж/Д',
    chainOrder: 4,
    classification: INFRA_CLASS.RELATIONSHIP_VERIFIED,
    sourceId: SRC.bogatyrCpt,
  }),
  node({
    id: 'bogatyr-ekibastuz',
    producerId: 'bogatyr',
    nodeType: INFRA_NODE_TYPE.RAIL_STATION,
    displayName: 'Экибастуз-2 / Экибастуз-3',
    categoryLabel: 'Ж/Д',
    chainOrder: 5,
    classification: INFRA_CLASS.RELATIONSHIP_VERIFIED,
    sourceId: SRC.bogatyrCpt,
    limitations: 'Связь со станциями не доказывает маршрут до конечного рынка.',
  }),
  node({
    id: 'bogatyr-gap',
    producerId: 'bogatyr',
    nodeType: INFRA_NODE_TYPE.DATA_GAP,
    displayName: 'Граница / терминал / рынок',
    categoryLabel: 'ПРОБЕЛ',
    chainOrder: 6,
    classification: INFRA_CLASS.DATA_GAP,
    notes: 'Дальнейшая связь не подтверждена.',
    limitations: 'Нет наблюдения именованной границы, терминала или конечного рынка с привязкой к этому производителю.',
  }),
  node({
    id: 'bogatyr-astana-trial',
    producerId: 'bogatyr',
    nodeType: INFRA_NODE_TYPE.SUPPLY_DIRECTION,
    displayName: 'ТЭЦ-2 Астана (пробная поставка 2022)',
    categoryLabel: 'КОНТЕКСТ',
    chainOrder: null,
    classification: INFRA_CLASS.HISTORICAL,
    sourceId: SRC.bogatyrCpt,
    notes: 'Отдельная пробная поставка 2022. Не канонический маршрут.',
  }),
  node({
    id: 'shubarkol-producer',
    producerId: 'shubarkol',
    nodeType: INFRA_NODE_TYPE.PRODUCER,
    displayName: 'АО «Шубарколь Комир»',
    categoryLabel: 'ПРОИЗВОДИТЕЛЬ',
    chainOrder: null,
    classification: INFRA_CLASS.RELATIONSHIP_VERIFIED,
    sourceId: SRC.shubarkolErg,
  }),
  node({
    id: 'shubarkol-mines',
    producerId: 'shubarkol',
    nodeType: INFRA_NODE_TYPE.MINE,
    displayName: 'Центральный / Западный разрез',
    categoryLabel: 'ДОБЫЧА',
    chainOrder: 1,
    classification: INFRA_CLASS.RELATIONSHIP_VERIFIED,
    sourceId: SRC.shubarkolErg,
    limitations: 'Производственная мощность 16,9 млн т/год не является инфраструктурной мощностью.',
  }),
  node({
    id: 'shubarkol-internal',
    producerId: 'shubarkol',
    nodeType: INFRA_NODE_TYPE.RAIL_STATION,
    displayName: 'Породная / Центральная / Западная',
    categoryLabel: 'ПОГРУЗКА',
    chainOrder: 2,
    classification: INFRA_CLASS.QUANTITATIVE_VERIFIED,
    sourceId: SRC.kaseShukAr2023,
  }),
  node({
    id: 'shubarkol-national-stations',
    producerId: 'shubarkol',
    nodeType: INFRA_NODE_TYPE.RAIL_STATION,
    displayName: 'Кызылжар / Шубарколь',
    categoryLabel: 'Ж/Д',
    chainOrder: 3,
    classification: INFRA_CLASS.RELATIONSHIP_VERIFIED,
    sourceId: SRC.kaseShukAr2023,
  }),
  node({
    id: 'shubarkol-direction',
    producerId: 'shubarkol',
    nodeType: INFRA_NODE_TYPE.SUPPLY_DIRECTION,
    displayName: 'Внутреннее / экспортное направление',
    categoryLabel: 'НАПРАВЛЕНИЕ',
    chainOrder: 4,
    classification: INFRA_CLASS.QUANTITATIVE_VERIFIED,
    sourceId: SRC.ktzShubarkolExport2025,
    limitations: 'Направление не именует границу, терминал или конечный рынок.',
  }),
  node({
    id: 'shubarkol-gap',
    producerId: 'shubarkol',
    nodeType: INFRA_NODE_TYPE.DATA_GAP,
    displayName: 'Граница / терминал / рынок',
    categoryLabel: 'ПРОБЕЛ',
    chainOrder: 5,
    classification: INFRA_CLASS.DATA_GAP,
    notes: 'Дальнейшая связь не подтверждена.',
  }),
  node({
    id: 'karazhyra-producer',
    producerId: 'karazhyra',
    nodeType: INFRA_NODE_TYPE.PRODUCER,
    displayName: 'АО «Каражыра»',
    categoryLabel: 'ПРОИЗВОДИТЕЛЬ',
    chainOrder: null,
    classification: INFRA_CLASS.RELATIONSHIP_VERIFIED,
    sourceId: SRC.karazhyraAbout,
  }),
  node({
    id: 'karazhyra-mine',
    producerId: 'karazhyra',
    nodeType: INFRA_NODE_TYPE.MINE,
    displayName: 'Разрез Каражыра',
    categoryLabel: 'ДОБЫЧА',
    chainOrder: 1,
    classification: INFRA_CLASS.RELATIONSHIP_VERIFIED,
    sourceId: SRC.karazhyraAbout,
    limitations: 'Формулировка «7,5–8 млн т/год» не является официальной заявленной мощностью.',
  }),
  node({
    id: 'karazhyra-processing',
    producerId: 'karazhyra',
    nodeType: INFRA_NODE_TYPE.PROCESSING,
    displayName: 'Сортировка / обогащение',
    categoryLabel: 'ОБРАБОТКА',
    chainOrder: 2,
    classification: INFRA_CLASS.RELATIONSHIP_VERIFIED,
    sourceId: SRC.karazhyraAbout,
    limitations: 'Обозначения ДСОК-1000/700 и СК-700 не читаются как т/час.',
  }),
  node({
    id: 'karazhyra-loading',
    producerId: 'karazhyra',
    nodeType: INFRA_NODE_TYPE.LOADING,
    displayName: 'Прямая погрузка в вагоны',
    categoryLabel: 'ПОГРУЗКА',
    chainOrder: 3,
    classification: INFRA_CLASS.RELATIONSHIP_VERIFIED,
    sourceId: SRC.karazhyraAbout,
  }),
  node({
    id: 'karazhyra-degelen',
    producerId: 'karazhyra',
    nodeType: INFRA_NODE_TYPE.RAIL_STATION,
    displayName: 'Дегелен / Угольная',
    categoryLabel: 'Ж/Д',
    chainOrder: 4,
    classification: INFRA_CLASS.QUANTITATIVE_VERIFIED,
    sourceId: SRC.ktzKarazhyraDegelen2025,
    limitations: 'Суточная заявка и средняя погрузка — разные наблюдения и не заявленная пропускная способность.',
  }),
  node({
    id: 'karazhyra-eko',
    producerId: 'karazhyra',
    nodeType: INFRA_NODE_TYPE.SUPPLY_DIRECTION,
    displayName: 'Семей–Курчатов / Восточный Казахстан',
    categoryLabel: 'НАПРАВЛЕНИЕ',
    chainOrder: 5,
    classification: INFRA_CLASS.QUANTITATIVE_VERIFIED,
    sourceId: SRC.ktzKarazhyraDegelen2025,
    limitations: 'Не экспортная граница и не конечный рынок.',
  }),
  node({
    id: 'karazhyra-gap',
    producerId: 'karazhyra',
    nodeType: INFRA_NODE_TYPE.DATA_GAP,
    displayName: 'Экспортная граница / рынок',
    categoryLabel: 'ПРОБЕЛ',
    chainOrder: 6,
    classification: INFRA_CLASS.DATA_GAP,
    notes: 'Дальнейшая связь не подтверждена.',
  }),
  node({
    id: 'karazhyra-oskemen-context',
    producerId: 'karazhyra',
    nodeType: INFRA_NODE_TYPE.SUPPLY_DIRECTION,
    displayName: 'Усть-Каменогорск / тупики',
    categoryLabel: 'КОНТЕКСТ',
    chainOrder: null,
    classification: INFRA_CLASS.PARTIAL,
    sourceId: SRC.ktzKarazhyraDegelen2025,
    limitations: 'Количества терминала нельзя полностью приписывать Каражыре.',
  }),
  node({
    id: 'maikuben-producer',
    producerId: 'maikuben',
    nodeType: INFRA_NODE_TYPE.PRODUCER,
    displayName: 'АО «Майкубен-Вест»',
    categoryLabel: 'ПРОИЗВОДИТЕЛЬ',
    chainOrder: null,
    classification: INFRA_CLASS.RELATIONSHIP_VERIFIED,
    sourceId: SRC.maikubenCompany,
  }),
  node({
    id: 'maikuben-mine',
    producerId: 'maikuben',
    nodeType: INFRA_NODE_TYPE.MINE,
    displayName: 'Разрез Майкубенский',
    categoryLabel: 'ДОБЫЧА',
    chainOrder: 1,
    classification: INFRA_CLASS.RELATIONSHIP_VERIFIED,
    sourceId: SRC.maikubenCompany,
    limitations: 'Проектная мощность 5,2 млн т/год не является инфраструктурной мощностью.',
  }),
  node({
    id: 'maikuben-internal',
    producerId: 'maikuben',
    nodeType: INFRA_NODE_TYPE.PROCESSING,
    displayName: 'Склад / ДСК / внутренняя ж/д',
    categoryLabel: 'ОБРАБОТКА',
    chainOrder: 2,
    classification: INFRA_CLASS.RELATIONSHIP_VERIFIED,
    sourceId: SRC.maikubenCompany,
    limitations: 'Текущая фактическая нагрузка не опубликована.',
  }),
  node({
    id: 'maikuben-ushkulyn',
    producerId: 'maikuben',
    nodeType: INFRA_NODE_TYPE.RAIL_STATION,
    displayName: 'Ушкулын',
    categoryLabel: 'Ж/Д',
    chainOrder: 3,
    classification: INFRA_CLASS.RELATIONSHIP_VERIFIED,
    sourceId: SRC.maikubenCompany,
  }),
  node({
    id: 'maikuben-maikain',
    producerId: 'maikuben',
    nodeType: INFRA_NODE_TYPE.RAIL_STATION,
    displayName: 'Майкаин',
    categoryLabel: 'Ж/Д',
    chainOrder: 4,
    classification: INFRA_CLASS.RELATIONSHIP_VERIFIED,
    sourceId: SRC.maikubenCompany,
  }),
  node({
    id: 'maikuben-mainline',
    producerId: 'maikuben',
    nodeType: INFRA_NODE_TYPE.RAIL_SECTION,
    displayName: 'Магистраль Астана–Павлодар',
    categoryLabel: 'НАПРАВЛЕНИЕ',
    chainOrder: 5,
    classification: INFRA_CLASS.RELATIONSHIP_VERIFIED,
    sourceId: SRC.maikubenCompany,
    limitations: 'Существование выхода не доказывает фактическую нагрузку, границу или рынок.',
  }),
  node({
    id: 'maikuben-gap',
    producerId: 'maikuben',
    nodeType: INFRA_NODE_TYPE.DATA_GAP,
    displayName: 'Граница / терминал / рынок',
    categoryLabel: 'ПРОБЕЛ',
    chainOrder: 6,
    classification: INFRA_CLASS.DATA_GAP,
    notes: 'Дальнейшая связь не подтверждена.',
    limitations: 'Упоминания Польши и Узбекистана — рыночный контекст, не подтверждённый маршрут.',
  }),
  node({
    id: 'maikuben-market-context',
    producerId: 'maikuben',
    nodeType: INFRA_NODE_TYPE.SUPPLY_DIRECTION,
    displayName: 'Европа / Узбекистан (контекст рынка)',
    categoryLabel: 'КОНТЕКСТ',
    chainOrder: null,
    classification: INFRA_CLASS.CONTEXT_ONLY,
    sourceId: SRC.kaseMkbwAr,
  }),
])

export const INFRASTRUCTURE_LINKS = Object.freeze([
  link({
    id: 'bogatyr-mine-cpt',
    producerId: 'bogatyr',
    fromId: 'bogatyr-mine',
    toId: 'bogatyr-cpt',
    relationshipType: INFRA_RELATION.PROCESSES_AT,
    classification: INFRA_CLASS.RELATIONSHIP_VERIFIED,
    sourceId: SRC.bogatyrCpt,
    statement: 'Разрез Богатырь связан с циклично-поточным комплексом предприятия.',
  }),
  link({
    id: 'bogatyr-cpt-loading',
    producerId: 'bogatyr',
    fromId: 'bogatyr-cpt',
    toId: 'bogatyr-loading',
    relationshipType: INFRA_RELATION.LOADS_AT,
    classification: INFRA_CLASS.RELATIONSHIP_VERIFIED,
    sourceId: SRC.bogatyrCpt,
    statement: 'ЦПТ включает автоматический пункт вагонной погрузки.',
  }),
  link({
    id: 'bogatyr-loading-collection',
    producerId: 'bogatyr',
    fromId: 'bogatyr-loading',
    toId: 'bogatyr-collection',
    relationshipType: INFRA_RELATION.SHIPS_VIA,
    classification: INFRA_CLASS.RELATIONSHIP_VERIFIED,
    sourceId: SRC.bogatyrCpt,
    statement: 'Погрузка выходит на сборочные станции предприятия.',
  }),
  link({
    id: 'bogatyr-collection-ekibastuz',
    producerId: 'bogatyr',
    fromId: 'bogatyr-collection',
    toId: 'bogatyr-ekibastuz',
    relationshipType: INFRA_RELATION.CONNECTED_TO,
    classification: INFRA_CLASS.RELATIONSHIP_VERIFIED,
    sourceId: SRC.bogatyrCpt,
    statement: 'Сборочные станции Богатыря связаны со станциями Экибастуз-2 / Экибастуз-3.',
  }),
  link({
    id: 'shubarkol-mines-internal',
    producerId: 'shubarkol',
    fromId: 'shubarkol-mines',
    toId: 'shubarkol-internal',
    relationshipType: INFRA_RELATION.LOADS_AT,
    classification: INFRA_CLASS.RELATIONSHIP_VERIFIED,
    sourceId: SRC.kaseShukAr2023,
    statement: 'Разрезы связаны с внутренними станциями Породная, Центральная, Западная.',
  }),
  link({
    id: 'shubarkol-internal-national',
    producerId: 'shubarkol',
    fromId: 'shubarkol-internal',
    toId: 'shubarkol-national-stations',
    relationshipType: INFRA_RELATION.CONNECTED_TO,
    classification: INFRA_CLASS.RELATIONSHIP_VERIFIED,
    sourceId: SRC.kaseShukAr2023,
    statement: 'Частная сеть примыкает к национальной инфраструктуре на станциях Кызылжар и Шубарколь.',
  }),
  link({
    id: 'shubarkol-national-direction',
    producerId: 'shubarkol',
    fromId: 'shubarkol-national-stations',
    toId: 'shubarkol-direction',
    relationshipType: INFRA_RELATION.SUPPLIES_TOWARD,
    classification: INFRA_CLASS.QUANTITATIVE_VERIFIED,
    sourceId: SRC.ktzShubarkolExport2025,
    statement: 'Опубликованы внутреннее и экспортное направления погрузки за июнь 2025.',
  }),
  link({
    id: 'karazhyra-mine-processing',
    producerId: 'karazhyra',
    fromId: 'karazhyra-mine',
    toId: 'karazhyra-processing',
    relationshipType: INFRA_RELATION.PROCESSES_AT,
    classification: INFRA_CLASS.RELATIONSHIP_VERIFIED,
    sourceId: SRC.karazhyraAbout,
    statement: 'На разрезе используются дробильно-сортировочные и обогатительные комплексы.',
  }),
  link({
    id: 'karazhyra-processing-loading',
    producerId: 'karazhyra',
    fromId: 'karazhyra-processing',
    toId: 'karazhyra-loading',
    relationshipType: INFRA_RELATION.LOADS_AT,
    classification: INFRA_CLASS.RELATIONSHIP_VERIFIED,
    sourceId: SRC.karazhyraAbout,
    statement: 'Отсортированный уголь грузится непосредственно в железнодорожные вагоны.',
  }),
  link({
    id: 'karazhyra-loading-degelen',
    producerId: 'karazhyra',
    fromId: 'karazhyra-loading',
    toId: 'karazhyra-degelen',
    relationshipType: INFRA_RELATION.SHIPS_VIA,
    classification: INFRA_CLASS.QUANTITATIVE_VERIFIED,
    sourceId: SRC.ktzKarazhyraDegelen2025,
    statement: 'КТЖ фиксирует погрузку угля на станции Дегелен в контексте АО «Каражыра».',
  }),
  link({
    id: 'karazhyra-degelen-eko',
    producerId: 'karazhyra',
    fromId: 'karazhyra-degelen',
    toId: 'karazhyra-eko',
    relationshipType: INFRA_RELATION.SUPPLIES_TOWARD,
    classification: INFRA_CLASS.QUANTITATIVE_VERIFIED,
    sourceId: SRC.ktzKarazhyraDegelen2025,
    statement: 'Опубликована погрузка в направлении Восточно-Казахстанской области.',
  }),
  link({
    id: 'maikuben-mine-internal',
    producerId: 'maikuben',
    fromId: 'maikuben-mine',
    toId: 'maikuben-internal',
    relationshipType: INFRA_RELATION.PROCESSES_AT,
    classification: INFRA_CLASS.RELATIONSHIP_VERIFIED,
    sourceId: SRC.maikubenCompany,
    statement: 'Разрез использует внутренний склад, ДСК и железнодорожную погрузку.',
  }),
  link({
    id: 'maikuben-internal-ushkulyn',
    producerId: 'maikuben',
    fromId: 'maikuben-internal',
    toId: 'maikuben-ushkulyn',
    relationshipType: INFRA_RELATION.CONNECTED_TO,
    classification: INFRA_CLASS.RELATIONSHIP_VERIFIED,
    sourceId: SRC.maikubenCompany,
    statement: 'Месторождение связано железнодорожной веткой со станцией Ушкулын.',
  }),
  link({
    id: 'maikuben-ushkulyn-maikain',
    producerId: 'maikuben',
    fromId: 'maikuben-ushkulyn',
    toId: 'maikuben-maikain',
    relationshipType: INFRA_RELATION.CONNECTED_TO,
    classification: INFRA_CLASS.RELATIONSHIP_VERIFIED,
    sourceId: SRC.maikubenCompany,
    statement: 'Ветка выходит на станцию Майкаин.',
  }),
  link({
    id: 'maikuben-maikain-mainline',
    producerId: 'maikuben',
    fromId: 'maikuben-maikain',
    toId: 'maikuben-mainline',
    relationshipType: INFRA_RELATION.SHIPS_VIA,
    classification: INFRA_CLASS.RELATIONSHIP_VERIFIED,
    sourceId: SRC.maikubenCompany,
    statement: 'Разрез имеет железнодорожный выход на магистраль Астана–Павлодар.',
  }),
])

export const INFRASTRUCTURE_OBSERVATIONS = Object.freeze([
  obs({
    id: 'bogatyr-cpt-length',
    producerId: 'bogatyr',
    nodeId: 'bogatyr-cpt',
    value: 11.5,
    unit: 'км',
    label: 'Протяжённость конвейерного комплекса ЦПТ',
    measureKind: INFRA_MEASURE.PHYSICAL_EXTENT,
    periodLabel: 'опубликовано 2022',
    classification: INFRA_CLASS.QUANTITATIVE_VERIFIED,
    sourceId: SRC.bogatyrCpt,
    statement: 'Опубликованная протяжённость конвейерного комплекса 11,5 км.',
    limitations: 'Не железнодорожная мощность и не объём выпуска.',
    primary: true,
  }),
  obs({
    id: 'bogatyr-storage-2024',
    producerId: 'bogatyr',
    nodeId: 'bogatyr-cpt',
    value: 280000,
    unit: 'т',
    label: 'Совокупный объём построенных угольных складов',
    measureKind: INFRA_MEASURE.STORAGE_VOLUME,
    periodLabel: 'август 2024',
    classification: INFRA_CLASS.QUANTITATIVE_VERIFIED,
    sourceId: SRC.bogatyrStorage2024,
    statement: 'Совокупный объём построенных складов 280 000 т.',
    limitations: 'Не годовой пропуск и не свободная ёмкость.',
  }),
  obs({
    id: 'bogatyr-loading-feb-2025',
    producerId: 'bogatyr',
    nodeId: 'bogatyr-loading',
    value: 3.9,
    unit: 'млн т',
    label: 'Погрузка угля, февраль 2025',
    measureKind: INFRA_MEASURE.MONTHLY_LOADING,
    periodLabel: 'февраль 2025',
    classification: INFRA_CLASS.QUANTITATIVE_VERIFIED,
    sourceId: SRC.ktzBogatyrLoading2025,
    statement: 'Фактически погруженный объём 3,9 млн т за февраль 2025.',
    limitations: 'Не годовая мощность и не гарантированный темп.',
    primary: true,
  }),
  obs({
    id: 'bogatyr-loading-complex-historical',
    producerId: 'bogatyr',
    nodeId: 'bogatyr-loading',
    value: 14,
    unit: 'млн т/год',
    label: 'Производительность погрузочного комплекса после реконструкции 2001–2004',
    measureKind: INFRA_MEASURE.PROJECT_CAPACITY,
    periodLabel: 'реконструкция 2001–2004',
    classification: INFRA_CLASS.HISTORICAL,
    sourceId: SRC.bogatyrCpt,
    statement: 'Историческая производительность погрузочного комплекса 14 млн т/год.',
    limitations: 'Не текущая полная производительность цепи и не текущая инфраструктурная мощность.',
    current: false,
  }),
  obs({
    id: 'shubarkol-stations',
    producerId: 'shubarkol',
    nodeId: 'shubarkol-internal',
    value: 3,
    unit: 'станций',
    label: 'Внутренние станции предприятия',
    measureKind: INFRA_MEASURE.STATION_COUNT,
    periodLabel: 'отчёт 2023',
    classification: INFRA_CLASS.QUANTITATIVE_VERIFIED,
    sourceId: SRC.kaseShukAr2023,
    statement: 'Три внутренние станции: Породная, Центральная, Западная.',
    limitations: 'Не длина путей, не фактическая нагрузка и не заявленная пропускная способность.',
  }),
  obs({
    id: 'shubarkol-sidings',
    producerId: 'shubarkol',
    nodeId: 'shubarkol-internal',
    value: 5,
    unit: 'подъездных путей',
    label: 'Подъездные пути предприятия',
    measureKind: INFRA_MEASURE.SIDING_COUNT,
    periodLabel: 'отчёт 2023',
    classification: INFRA_CLASS.QUANTITATIVE_VERIFIED,
    sourceId: SRC.kaseShukAr2023,
    statement: 'Пять подъездных путей.',
    limitations: 'Не фактическая нагрузка и не национальные 951 тупика.',
  }),
  obs({
    id: 'shubarkol-wagons-shift',
    producerId: 'shubarkol',
    nodeId: 'shubarkol-internal',
    value: 472,
    unit: 'вагонов/смену',
    label: 'Рекордная сменная отгрузка, октябрь 2024',
    measureKind: INFRA_MEASURE.WAGON_RATE,
    periodLabel: 'октябрь 2024',
    classification: INFRA_CLASS.QUANTITATIVE_VERIFIED,
    sourceId: SRC.shubarkolErg,
    statement: 'Рекордная сменная отгрузка 472 вагона.',
    limitations: 'Не заявленная пропускная способность и не устойчивый средний уровень.',
    primary: true,
  }),
  obs({
    id: 'shubarkol-export-jun-2025',
    producerId: 'shubarkol',
    nodeId: 'shubarkol-direction',
    value: 841000,
    unit: 'т',
    label: 'Экспортная погрузка по ж/д, июнь 2025',
    measureKind: INFRA_MEASURE.MONTHLY_LOADING,
    periodLabel: 'июнь 2025',
    classification: INFRA_CLASS.QUANTITATIVE_VERIFIED,
    sourceId: SRC.ktzShubarkolExport2025,
    statement: 'Месячная экспортная погрузка 841 000 т.',
    limitations: 'Не терминальная мощность и не конечный рынок.',
    primary: true,
  }),
  obs({
    id: 'shubarkol-total-jun-2025',
    producerId: 'shubarkol',
    nodeId: 'shubarkol-direction',
    value: 1.2,
    unit: 'млн т',
    qualifier: 'about',
    label: 'Общий месячный объём погрузки, июнь 2025',
    measureKind: INFRA_MEASURE.MONTHLY_LOADING,
    periodLabel: 'июнь 2025',
    classification: INFRA_CLASS.PARTIAL,
    sourceId: SRC.ktzShubarkolExport2025,
    statement: 'Опубликованный общий месячный объём около 1,2 млн т в той же публикации КТЖ.',
    limitations: 'Привязку охвата хранить с контекстом публикации; не годовая пропускная способность.',
  }),
  obs({
    id: 'shubarkol-domestic-jun-2025',
    producerId: 'shubarkol',
    nodeId: 'shubarkol-direction',
    value: 326000,
    unit: 'т',
    label: 'Внутреннее направление, июнь 2025',
    measureKind: INFRA_MEASURE.MONTHLY_LOADING,
    periodLabel: 'июнь 2025',
    classification: INFRA_CLASS.PARTIAL,
    sourceId: SRC.ktzShubarkolExport2025,
    statement: 'Опубликованный объём внутри Казахстана 326 000 т в той же публикации.',
    limitations: 'Контекст публикации; не годовая пропускная способность.',
  }),
  obs({
    id: 'karazhyra-request-350',
    producerId: 'karazhyra',
    nodeId: 'karazhyra-degelen',
    value: 350,
    unit: 'вагонов/сут',
    label: 'Суточная заявка на погрузку, станция Дегелен',
    measureKind: INFRA_MEASURE.WAGON_RATE,
    periodLabel: '17 октября 2025',
    classification: INFRA_CLASS.QUANTITATIVE_VERIFIED,
    sourceId: SRC.ktzKarazhyraDegelen2025,
    statement: 'При суточной заявке 350 вагонов.',
    limitations: 'Не заявленная пропускная способность. Не вычитать из средней погрузки. Не выводится ограничение узла.',
  }),
  obs({
    id: 'karazhyra-average-280',
    producerId: 'karazhyra',
    nodeId: 'karazhyra-degelen',
    value: 280,
    unit: 'вагонов/сут',
    label: 'Средняя погрузка, станция Дегелен',
    measureKind: INFRA_MEASURE.WAGON_RATE,
    periodLabel: '17 октября 2025',
    classification: INFRA_CLASS.QUANTITATIVE_VERIFIED,
    sourceId: SRC.ktzKarazhyraDegelen2025,
    statement: 'Компания загружает в среднем 280 вагонов.',
    limitations: 'Не заявленная пропускная способность. Не вычитать из заявки. Не свободная мощность.',
    primary: true,
  }),
  obs({
    id: 'karazhyra-oct-plan-wagons',
    producerId: 'karazhyra',
    nodeId: 'karazhyra-degelen',
    value: 10525,
    unit: 'вагонов',
    label: 'План погрузки на октябрь 2025, Казахстан',
    measureKind: INFRA_MEASURE.WAGON_COUNT,
    periodLabel: 'октябрь 2025',
    classification: INFRA_CLASS.QUANTITATIVE_VERIFIED,
    sourceId: SRC.ktzKarazhyraDegelen2025,
    statement: 'План: 10 525 вагонов по Казахстану в октябре.',
    limitations: 'Это план, не фактическое исполнение и не заявленная пропускная способность.',
  }),
  obs({
    id: 'karazhyra-oct-plan-tonnes',
    producerId: 'karazhyra',
    nodeId: 'karazhyra-degelen',
    value: 726.2,
    unit: 'тыс. т',
    label: 'План погрузки на октябрь 2025, Казахстан',
    measureKind: INFRA_MEASURE.TONNAGE,
    periodLabel: 'октябрь 2025',
    classification: INFRA_CLASS.QUANTITATIVE_VERIFIED,
    sourceId: SRC.ktzKarazhyraDegelen2025,
    statement: 'План: 726,2 тыс. т по Казахстану в октябре.',
    limitations: 'Это план, не фактическое исполнение и не заявленная пропускная способность.',
  }),
  obs({
    id: 'karazhyra-eko-wagons',
    producerId: 'karazhyra',
    nodeId: 'karazhyra-eko',
    value: 1944,
    unit: 'вагонов',
    label: 'Погрузка в ВКО за 1–15 октября 2025',
    measureKind: INFRA_MEASURE.WAGON_COUNT,
    periodLabel: '1–15 октября 2025',
    classification: INFRA_CLASS.QUANTITATIVE_VERIFIED,
    sourceId: SRC.ktzKarazhyraDegelen2025,
    statement: '1 944 полувагона в Восточно-Казахстанскую область за неполный месяц.',
    limitations: 'Не полный месяц, не приемка и не заявленная пропускная способность.',
    primary: true,
  }),
  obs({
    id: 'karazhyra-eko-tonnes',
    producerId: 'karazhyra',
    nodeId: 'karazhyra-eko',
    value: 134.6,
    unit: 'тыс. т',
    label: 'Погрузка в ВКО за 1–15 октября 2025',
    measureKind: INFRA_MEASURE.TONNAGE,
    periodLabel: '1–15 октября 2025',
    classification: INFRA_CLASS.QUANTITATIVE_VERIFIED,
    sourceId: SRC.ktzKarazhyraDegelen2025,
    statement: '134,6 тыс. т в Восточно-Казахстанскую область за неполный месяц.',
    limitations: 'Не полный месяц, не приемка и не заявленная пропускная способность.',
  }),
  obs({
    id: 'karazhyra-oskemen-context-rate',
    producerId: 'karazhyra',
    nodeId: 'karazhyra-oskemen-context',
    value: 15,
    unit: 'вагонов/сут',
    label: 'Отправка в направлении Усть-Каменогорска',
    measureKind: INFRA_MEASURE.WAGON_RATE,
    periodLabel: '17 октября 2025',
    classification: INFRA_CLASS.PARTIAL,
    sourceId: SRC.ktzKarazhyraDegelen2025,
    statement: 'Ежедневно отправляется по 15 вагонов на угольные тупики Сейком и ТК Терминал.',
    limitations: 'Не эксклюзивность источника и не заявленная пропускная способность терминала.',
  }),
  obs({
    id: 'maikuben-project-rail',
    producerId: 'maikuben',
    nodeId: 'maikuben-internal',
    value: 40,
    unit: 'км',
    label: 'Проектная подъездная железная дорога, 1988–1989',
    measureKind: INFRA_MEASURE.PROJECT_EXTENT,
    periodLabel: 'проект 1988–1989',
    classification: INFRA_CLASS.HISTORICAL,
    sourceId: SRC.maikubenHistory,
    statement: 'Проектом предусматривалось строительство подъездной железной дороги 40 км.',
    limitations: 'Не фактически построенная и не текущая рабочая длина.',
    current: false,
  }),
  obs({
    id: 'maikuben-project-dsk',
    producerId: 'maikuben',
    nodeId: 'maikuben-internal',
    value: 2.5,
    unit: 'млн т/год',
    label: 'Проектная мощность ДСК первой очереди, 1988–1989',
    measureKind: INFRA_MEASURE.PROJECT_CAPACITY,
    periodLabel: 'проект 1988–1989',
    classification: INFRA_CLASS.HISTORICAL,
    sourceId: SRC.maikubenHistory,
    statement: 'Проектом предусматривался ДСК 2,5 млн т/год.',
    limitations: 'Не текущая производительность и не показатель загрузки.',
    current: false,
  }),
])

export const INFRASTRUCTURE_FIXTURE = Object.freeze({
  nodes: INFRASTRUCTURE_NODES,
  links: INFRASTRUCTURE_LINKS,
  observations: INFRASTRUCTURE_OBSERVATIONS,
  sources: INFRASTRUCTURE_SOURCES,
})
